import { useEffect, useState } from "react";
import { JobsAPI, type Outreach } from "../../jobs/api";

const STATUSES = ["draft", "edited", "sent", "archived"];

export default function OutreachPage() {
  const [rows, setRows] = useState<Outreach[]>([]);
  const [filter, setFilter] = useState("");
  const [err, setErr] = useState<string | null>(null);

  const load = () => {
    JobsAPI.outreach(new URLSearchParams())
      .then(setRows).catch((e) => setErr(String(e)));
  };
  useEffect(load, []);

  const updateStatus = async (id: number, status: string) => {
    await JobsAPI.patchOutreach(id, { status });
    load();
  };
  const updateBody = async (id: number, body_md: string) => {
    await JobsAPI.patchOutreach(id, { body_md, status: "edited" });
    load();
  };

  const filtered = filter ? rows.filter((r) => r.kind === filter) : rows;

  return (
    <div className="h-full overflow-auto p-6 max-w-4xl mx-auto space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-semibold">Outreach drafts</h1>
        <select value={filter} onChange={(e) => setFilter(e.target.value)}
          className="bg-slate-900 border border-slate-700 rounded px-2 py-1 text-sm">
          <option value="">all kinds</option>
          <option value="recruiter_dm">recruiter_dm</option>
          <option value="referral_ask">referral_ask</option>
          <option value="hm_outreach">hm_outreach</option>
          <option value="followup">followup</option>
          <option value="thank_you">thank_you</option>
        </select>
      </div>
      {err && <div className="text-red-400 text-sm">{err}</div>}

      <div className="text-xs text-slate-500">
        Drafts are generated by Claude Code commands (see <code>.claude/commands/draft-outreach.md</code>).
        Nothing is sent automatically. Copy and send manually.
      </div>

      {filtered.map((d) => (
        <div key={d.id} className="rounded border border-slate-800 p-3">
          <div className="flex items-center gap-3 text-xs text-slate-400">
            <span className="text-[10px] px-1 border border-slate-700 rounded uppercase">{d.kind}</span>
            {d.subject && <span>{d.subject}</span>}
            <span className="ml-auto">{d.status}</span>
            <select value={d.status} onChange={(e) => updateStatus(d.id, e.target.value)}
              className="bg-slate-900 border border-slate-700 rounded px-1 py-0.5">
              {STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>
          <textarea
            defaultValue={d.body_md}
            onBlur={(e) => { if (e.target.value !== d.body_md) updateBody(d.id, e.target.value); }}
            className="mt-2 w-full bg-slate-950 border border-slate-800 rounded p-2 text-sm font-mono"
            rows={Math.min(14, Math.max(4, d.body_md.split("\n").length))}
          />
        </div>
      ))}
      {filtered.length === 0 && <div className="text-slate-500 text-sm">No drafts yet. Use <code>/draft-outreach</code> in Claude Code.</div>}
    </div>
  );
}
